### ISSUE TITLE
design_feed_flow overwritten by max_centrifuges

### ISSUE THREAD

**Issue by bam241** [CNERG/mbmore#15]
@mbmcgarry when trying to play with the `CascadeEnrich` using all the default parameters:
`design_feed_flow = 100kg/month`
`max_centrifuges = 1000`

the design ends up tolerating ~208kg/month to build a cascade with 997 centrifuges.

I feel like the design_feed_flow get overwritten to match the number of cascades required.

but when I try to increase the design_feed_flow above 208kg/month in the input file, then the algorithm complains: " there is not enough centrifuges to meet the demanded feed_flow"

is it a normal behavior ?

**Comment by bam241** [comment]
actually the behavior is stranger that described earlier:

| design_feed_flow | max_centrifuges | calculated_flow | used_centrifuges |
| ----------------- | ------------- | ------------- | ------------- |
| 10 | 1000  | ~206 | 986 |
| 100  | 1000 | ~208 | 997 |
| 150 | 1000  | ~201 | 963 |
| 180 | 1000  | ~208 | 998 |
| 190 | 1000  | 199.5 | 956 |
| 200 | 1000  | 200 | 958 |
| 207 | 1000  | 207 | 993 |
| 208 | 1000  | 208 | 997 |
| 300 | 1000  | ~203. | 971 |
| 500 | 1000  | ~208. | 996 |

**Comment by bam241** [comment]
looks like different response from an optimisation problem.
it was strange because when setting the feed_flow to a values close to the best solution it feel like no optimisation was done...

**Comment by mbmcgarry** [comment]
Is this resolved?  I wrote a very simple optimization. I will be in ERB on
Wed and we can discuss if you're still having trouble with it.

Meghan

On Oct 25, 2017 4:56 PM, "Mouginot Baptiste" <notifications@github.com>
wrote:

looks like different response from an optimisation problem.
it was strange because when setting the feed_flow to a values close to the
best solution it feel like no optimisation was done...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CNERG/mbmore/issues/15#issuecomment-339483942>, or mute
the thread

**Comment by bam241** [comment]
yes this should be ok :)

I was just surprise because of the results on the 200. Be this is consistant for me!
